import { StyleSheet } from 'react-native';

export const travelStyles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: '#F8FAFC',
  },
  container: {
    paddingHorizontal: 16,
    paddingBottom: 24,
    paddingTop: 12,
    gap: 14,
  },
  card: {
    borderRadius: 16,
    backgroundColor: '#FFFFFF',
    padding: 14,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    shadowColor: '#0F172A',
    shadowOpacity: 0.06,
    shadowRadius: 8,
    elevation: 1,
    gap: 8,
  },
  heading: {
    fontSize: 22,
    fontWeight: '700',
    color: '#0F172A',
  },
  subheading: {
    fontSize: 14,
    color: '#64748B',
  },
  timelineCard: {
    borderRadius: 16,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E5E7EB',
    padding: 14,
    gap: 8,
  },
  timelineRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  timelineTime: {
    width: 56,
    textAlign: 'center',
    color: '#FFFFFF',
    backgroundColor: '#0EA5E9',
    borderRadius: 12,
    paddingVertical: 4,
    fontSize: 12,
    fontWeight: '700',
  },
  timelineText: {
    color: '#0F172A',
    fontSize: 14,
    fontWeight: '600',
  },
  divider: {
    height: 1,
    backgroundColor: '#E2E8F0',
  },
  rowWrap: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  chipWrap: {
    flexDirection: 'row',
    gap: 8,
    marginTop: 8,
    flexWrap: 'wrap',
  },
  chip: {
    backgroundColor: '#EAF2FF',
    borderWidth: 1,
    borderColor: '#BFDBFE',
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 999,
  },
  chipText: {
    fontSize: 12,
    color: '#1E40AF',
    fontWeight: '700',
  },
  pillButton: {
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 999,
    paddingVertical: 8,
    paddingHorizontal: 14,
    backgroundColor: '#FFFFFF',
  },
  pillText: {
    color: '#334155',
    fontWeight: '600',
  },
  primaryButton: {
    borderRadius: 12,
    backgroundColor: '#F97316',
    paddingVertical: 12,
    paddingHorizontal: 16,
    alignItems: 'center',
    shadowColor: '#EA580C',
    shadowOpacity: 0.25,
    shadowRadius: 8,
    elevation: 2,
  },
  primaryButtonText: {
    color: '#FFFFFF',
    fontWeight: '700',
  },
  horizontalSection: {
    gap: 10,
  },
  sectionTitle: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  sectionTitleText: {
    fontSize: 18,
    fontWeight: '700',
    color: '#0F172A',
  },
  button: {
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    padding: 12,
    gap: 4,
  },
  buttonTitle: {
    color: '#0F172A',
    fontWeight: '700',
    fontSize: 15,
  },
  buttonDescription: {
    color: '#64748B',
    fontSize: 12,
    lineHeight: 18,
  },
  input: {
    borderWidth: 1,
    borderColor: '#CBD5E1',
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 10,
    marginTop: 8,
    backgroundColor: '#FFFFFF',
    color: '#0F172A',
  },
  detailSection: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E5E7EB',
    borderRadius: 16,
    padding: 14,
    gap: 10,
  },
  sectionBody: {
    color: '#334155',
    lineHeight: 22,
  },
  accentText: {
    color: '#F97316',
    fontWeight: '700',
  },
});
